<script setup lang="ts">
const set1 = ref<string[]>()
</script>

<template>
  <div class="flex flex-col gap-[18px]">
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category1"
      for-label="category1"
      value="Категория1"
      label="Категория1"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category2"
      for-label="category2"
      value="Категория2"
      label="Категория2"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category3"
      for-label="category3"
      value="Категория3"
      label="Категория3"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category4"
      for-label="category4"
      value="Категория4"
      label="Категория4"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category5"
      for-label="category5"
      value="Категория5"
      label="Категория5"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category6"
      for-label="category6"
      value="Категория6"
      label="Категория6"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category7"
      for-label="category7"
      value="Категория7"
      label="Категория7"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category8"
      for-label="category8"
      value="Категория8"
      label="Категория8"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category9"
      for-label="category9"
      value="Категория9"
      label="Категория9"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category10"
      for-label="category10"
      value="Категория10"
      label="Категория10"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category11"
      for-label="category11"
      value="Категория11"
      label="Категория11"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category12"
      for-label="category12"
      value="Категория12"
      label="Категория12"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category13"
      for-label="category13"
      value="Категория13"
      label="Категория13"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category14"
      for-label="category14"
      value="Категория14"
      label="Категория14"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category15"
      for-label="category15"
      value="Категория15"
      label="Категория15"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category16"
      for-label="category16"
      value="Категория16"
      label="Категория16"
    />
    <ui-checkbox
      v-model="set1"
      name="set1"
      input-id="category17"
      for-label="category17"
      value="Категория17"
      label="Категория17"
    />
  </div>
</template>
